import {
  Server,
  Database,
  Users,
  Activity,
  DollarSign,
  MapPin,
  Cloud,
  Cpu,
  Globe,
  Lock,
  Zap,
  BarChart3,
  GitBranch,
  Target,
  Network,
} from 'lucide-react';

export const NODE_ICON_MAP: Record<string, React.ReactNode> = {
  server: <Server className="w-4 h-4" />,
  database: <Database className="w-4 h-4" />,
  users: <Users className="w-4 h-4" />,
  activity: <Activity className="w-4 h-4" />,
  dollar: <DollarSign className="w-4 h-4" />,
  map: <MapPin className="w-4 h-4" />,
  cloud: <Cloud className="w-4 h-4" />,
  cpu: <Cpu className="w-4 h-4" />,
  globe: <Globe className="w-4 h-4" />,
  lock: <Lock className="w-4 h-4" />,
  zap: <Zap className="w-4 h-4" />,
  chart: <BarChart3 className="w-4 h-4" />,
  git: <GitBranch className="w-4 h-4" />,
  target: <Target className="w-4 h-4" />,
  network: <Network className="w-4 h-4" />,
};
